title: painting
description: >
  Project website. All my projects bundled into one, here you can check out my projects and check what you want to use maybe.
  I like to use css, javascript, npm, bootstrap, symfony, jekyll and such.
baseurl: "/painting"
url: "https://sterfgithub.github.io"
#twitter_username: sterfgithub
#github_username:  sterfgithub

markdown: kramdown
# host: 0.0.0.0

google_analytics: 

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - assets
  - LICENSE
  - package.json
  - package-lock.json
  - README.md
  - webpack.config.js
  - gulpfile.js
